/** @packageDocumentation
 * Speech-CloudMicrosoft Version und Build Konstanten
 *
 * @module cloud-microsoft
 * @author SB
 */


export const CLOUDMICROSOFT_VERSION_NUMBER = '0.2.1';
export const CLOUDMICROSOFT_VERSION_BUILD = '0005';
export const CLOUDMICROSOFT_VERSION_TYPE = 'ALPHA';
export const CLOUDMICROSOFT_VERSION_DATE = '26.10.2020';
// tslint:disable-next-line
export const CLOUDMICROSOFT_VERSION_STRING = CLOUDMICROSOFT_VERSION_NUMBER + '.' + CLOUDMICROSOFT_VERSION_BUILD + ' vom ' + CLOUDMICROSOFT_VERSION_DATE + ' (' + CLOUDMICROSOFT_VERSION_TYPE + ')';

export const CLOUDMICROSOFT_SERVER_VERSION = CLOUDMICROSOFT_VERSION_STRING;
export const CLOUDMICROSOFT_WORKER_VERSION = CLOUDMICROSOFT_VERSION_STRING;
export const CLOUDMICROSOFT_API_VERSION = CLOUDMICROSOFT_VERSION_STRING;
